# Generated by Django 5.2.2 on 2025-06-04 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DialogueState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('current_step', models.IntegerField(default=0)),
                ('user_name', models.CharField(blank=True, max_length=100)),
                ('paused', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('dialogue_data', models.JSONField(default=dict)),
            ],
        ),
    ]
