# Generated by Django 5.2.2 on 2025-06-05 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dialogue', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DialogueState',
        ),
    ]
